title: Matthew Yoshinori Otani McKinney
description: Matthew McKinney is a Masters Student at BYU researching applications of Machine Learning in Scatterometry
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
